name: CI Workflow

# Trigger the workflow on push to 'master' branch and pull requests targeting 'master'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (replace with other environments if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (replace with the appropriate command for your project)
      - name: Run tests
        run: npm test

      # Deploy (This can be customized for your deployment process)
      - name: Deploy
        run: echo "Deploying application..."
        # Add your deployment scripts or actions here
